"""empty message

Revision ID: 794f6853eed1
Revises: a85afe86888a
Create Date: 2017-02-24 10:01:18.996861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794f6853eed1'
down_revision = 'a85afe86888a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snippets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('code_type_id', sa.SmallInteger(), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snippets_date_posted'), 'snippets', ['date_posted'], unique=False)
    op.create_table('snippet_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('snippet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['snippet_id'], ['snippets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snippet_comments_date_posted'), 'snippet_comments', ['date_posted'], unique=False)
    op.drop_column(u'comments', 'body_html')
    op.drop_column(u'posts', 'body_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'posts', sa.Column('body_html', sa.TEXT(), nullable=True))
    op.add_column(u'comments', sa.Column('body_html', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_snippet_comments_date_posted'), table_name='snippet_comments')
    op.drop_table('snippet_comments')
    op.drop_index(op.f('ix_snippets_date_posted'), table_name='snippets')
    op.drop_table('snippets')
    # ### end Alembic commands ###
